add styles to negative-search
KovalenkoMaks/goIt-news-team-project pull request #59
Opened 2023-02-12 21:59 UTC by YevgeniiaP

2023-02-12 22:18 UTC, KovalenkoMaks requested changes

2023-02-12 22:18 UTC, KovalenkoMaks commented on src/sass/base/_reset.scss
> +  height: auto;
измени высоту только в своем стиле, мы с картинками много мучались, чтобы не поламались все карты. задай просто точечно только для себя

2023-02-12 22:26 UTC, YevgeniiaP commented on src/sass/base/_reset.scss
> +  height: auto;
виправила

2023-02-13 07:06 UTC, KovalenkoMaks approved these changes

2023-02-13 07:06 UTC, merged